### PR TITLE
Extend the README

### PR DESCRIPTION
**Pull request by samiraguiar**
Provide a short introduction/overview to guibot to make it easier
for newcomers to understand what guibot is about.

In the future it would be nice to also add a short example and a
video of the tool in action.

### CODE REVIEW

**Comment by samiraguiar** [comment]
> I am not sure I like this description as I like the original one which sounds more formal and appropriate for one-line description on Github. Both computer vision and desktop control sides have backends, "locate objects" is too abstract as "locate targets on the screen" might be better but again rather in the Introduction, etc.

I agree, the description is too long. I wanted to drop the "backend" from the description though as it's sound too implementation-defined, maybe even unneeded for the reader skimming through repository titles. One idea is to replace it by "techniques" or "technologies", but it might even be left out.

Also, the fact that it's GUI-agnostic is a good selling point that we should somehow mention in the short description. [Most of the other GUI automation](https://en.wikipedia.org/wiki/Comparison_of_GUI_testing_tools) tools work on one or two platforms only, while we can automate anything, even Android, iOS or embedded systems. We kind of express that with "different desktop control backends", but I think this is too vague. Here's an example:

> https://www.froglogic.com/squish/
> The GUI Test Automation Tool for all kinds of cross-platform desktop, mobile, embedded and web applications.

How could we improve a description like:
> guibot - Automate any GUI using computer vision

to cover all of our points?

**Comment by pevogam** [comment]
> > I am not sure I like this description as I like the original one which sounds more formal and appropriate for one-line description on Github. Both computer vision and desktop control sides have backends, "locate objects" is too abstract as "locate targets on the screen" might be better but again rather in the Introduction, etc.
> 
> I agree, the description is too long. I wanted to drop the "backend" from the description though as it's sound too implementation-defined, maybe even unneeded for the reader skimming through repository titles. One idea is to replace it by "techniques" or "technologies", but it might even be left out.

Offering a wide portfolio of backends and the free abstraction and selection thereof is one of the defining features of the project and differentiates it from regular GUI automation tools which focus on just one backend implementation. Then regarding about the term "backend", I think it is a reasonable word and used throughout the code base and documentation. Would you suggest "tecnhologies" as an alternative? What other alternatives could we think of?

> Also, the fact that it's GUI-agnostic is a good selling point that we should somehow mention in the short description. [Most of the other GUI automation](https://en.wikipedia.org/wiki/Comparison_of_GUI_testing_tools) tools work on one or two platforms only, while we can automate anything, even Android, iOS or embedded systems. We kind of express that with "different desktop control backends", but I think this is too vague. Here's an example:
> 
> > https://www.froglogic.com/squish/
> > The GUI Test Automation Tool for all kinds of cross-platform desktop, mobile, embedded and web applications.

Yes, this was precisely my point. In fact we have two selling points - one about a variety of simple and more advanced computer vision algorithms to find what we are looking for and a variety of desktop control implementations that allow us the second type of "agnostic". I do like the sample description you provided here too but it covers only one side of this.

> How could we improve a description like:
> 
> > guibot - Automate any GUI using computer vision
> 
> to cover all of our points?

Not sure what could be an improvement of the current description in a way other than changing the "backends" word.

"A tool for GUI automation using a variety of computer vision algorithms and platform agnostic controllers." ?
"A tool for GUI automation using a variety of computer vision algorithms and cross-platform implementations." ?

**Comment by samiraguiar** [comment]
I've fixed the points raised and reverted the description.
Apart from the already mentioned descriptions here and on the chat, I thought of these:
> Cross-platform GUI automation tool supporting a variety of computer vision and desktop control backends
> Cross-platform GUI automation tool with computer vision capabilities
> Cross-platform GUI automation using computer vision

Another reason I dislike "desktop control backends" is because we don't need a "desktop" - we can control a simple window or a mobile system.
So I'm out of ideas now :exploding_head: I'll leave it up to you to decide.

**Comment by pevogam** [comment]
> I've fixed the points raised and reverted the description.
> Apart from the already mentioned descriptions here and on the chat, I thought of these:
> 
> > Cross-platform GUI automation tool supporting a variety of computer vision and desktop control backends
> > Cross-platform GUI automation tool with computer vision capabilities
> > Cross-platform GUI automation using computer vision
> 
> Another reason I dislike "desktop control backends" is because we don't need a "desktop" - we can control a simple window or a mobile system.
> So I'm out of ideas now exploding_head I'll leave it up to you to decide.

Also a very good point, I also don't like the `desktop` and overall `desktop control` expressions.

Let's think about the shorter description some more in the coming week, it is not a blocker for the updated README.

**Pull request closed without merging**
